repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.2
    hooks:
      - id: ruff
        name: lint
        entry: ruff check --force-exclude
        language: python
        types_or:
          - python
          - pyi
        args: [--fix]
        require_serial: true
      - id: ruff-format
        name: format
        entry: ruff format --force-exclude
        language: python
        types_or:
          - python
          - pyi
        require_serial: true
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        entry: mypy
        language: python
        args: []
        require_serial: true
